### ISSUE TITLE
Workshop Withdrawl

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#49]
We should allow requester to withdraw workshop(Move to draft position). Once requester withdraw we need to unassign workshop from presenter and send email on the change in workshop status.
While he withdraw workshop we need to force user to provide reason for withdrawal of workshop.

**Comment by shankisg** [comment]
@vnbang2003 I would like to work on this. let me know if it's fine. If yes, it would be good if you can assign me.

**Comment by vnbang2003** [comment]
Done

**Comment by shankisg** [comment]
@vnbang2003 

Questions
- Can't we add to new status as **withdrawn**. On withdrawal, if we moving status to **draft*, How we can differentiate new  workshop request vs withdrawn workshop.

- In workshop update page, I can still see the status dropdown, organisations are going to use this.
Or a button on right hand side top beside **Edit workshop** button, in  workshop details page(recommended ) to withdraw workshop.

**Comment by vnbang2003** [comment]
New workshop will be in status "Requested".
organisation can changes status by button click no other options.

**Comment by vnbang2003** [comment]
@shankisg I think it done by button Hold  right ?
